name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python 3.11.1
      uses: actions/setup-python@v3
      with:
        python-version: 3.11.1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 poetry
        poetry install
    - name: Set up Mongo 5.0
      uses: supercharge/mongodb-github-action@1.8.0
      with:
        mongodb-version: '5.0'
        mongodb-username: root
        mongodb-password: example
        mongodb-db: shop-food
    - name: Lint with flake8
      run: |
        poetry run flake8 shop_food tests
    - name: Test with pytest
      run: |
        poetry run pytest tests
